### PR TITLE
Add person birth order

### PR DESCRIPTION
**Pull request by nafiesl**
User can update person birth order (like first child, second child, or as third child).

For existing silsilah user, please update update `users` table with this sql command:
```sql
ALTER TABLE `users`
	ADD COLUMN `birth_order` TINYINT(3) UNSIGNED NULL DEFAULT NULL AFTER `dob`;
```

### CODE REVIEW

**Comment by biplobice** [comment]
@nafiesl IMHO, it's better to add migration on your app.

**Comment by nafiesl** [comment]
@biplobice :grin: you were right. In best practice, we should have add migration file on every DB structure changes.

But currently, this project is still in development (even it is in slow progress). I just don't want to ended up with so much migration files because of small changes on existing tables.

Besides, I always keep inform the table changes (in sql command) in commit comments. Hope that exising silsilah users won't have any problem after pull the commit changes.

Glad to know yo have attention to this project. Thanks a lot.

**Comment by biplobice** [comment]
I had a plan to make something like this to keep my family history & I found it so much useful.
Thanks a lot for this project.

**Comment by nafiesl** [comment]
Your welcome @biplobice. Good to know that this project is usefull for uou.

**Pull request merged**
